config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :corks

  root "corks#index"
end

app/models/cork.rb
class Cork < ActiveRecord::Base
  belongs_to :user

  has_attached_file :image, styles:  { medium: "300x300>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :corks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/corks_controller.rb
class CorksController < ApplicationController
  before_action :find_cork, only: [:show, :edit, :update, :destroy]

  def index
    @corks = Cork.all.order("created_at DESC")
  end

  def show
  end

  def new
    @cork = current_user.corks.build
  end

  def create
    @cork = current_user.corks.build(cork_params)

    if @cork.save
      redirect_to @cork, notice: "Successfully created new Post"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @cork.update(cork_params)
      redirect_to @cork, notice: "Post was Successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @cork.destroy
    redirect_to root_path
  end

  private

  def cork_params
    params.require(:cork).permit(:title, :description)
  end

  def find_cork
    @cork = Cork.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corks_helper.rb
module CorksHelper
end

app/views/corks/_form.html.haml
= simple_form_for @cork, html: { multipart: true } do |f|
  - if @cork.errors.any?
    #errors
      %h2
      = pluralize(@cork.errors.count, "error")
      prevented this Cork from saving
      %ul
        - @cork.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :image, input_html: { class: 'form-control' }

  .form-group
    = f.input :title, input_html: { class: 'form-control' }

  .form-group
    = f.input :description, input_html: { class: 'form-control' }

  =f.button :submit, "Create Post!", class: "btn btn-primary"

app/views/corks/edit.html.haml
.col-md-6.col-md-offset-3
  %h1 Edit Cork
  = render 'form'
  = link_to "Cancel", cork_path

app/views/corks/index.html.haml
- @corks.each do |cork|
  %h2= link_to cork.title, cork

app/views/corks/new.html.haml
.col-md-6.col-md-offset-3
  %h1 New Form
  = render 'form'
  = link_to "Back", root_path

app/views/corks/show.html.haml
%h1= @cork.title
%p= @cork.description
%p
Submitted by
= @cork.user.email

%br/

= link_to "Back", root_path
= link_to "Edit", edit_cork_path
= link_to "Delete", cork_path, method: :delete, data: { confirm: "Are you sure?" }

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Cork Board
  = stylesheet_link_tag     'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag  'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Cork Board", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Post", new_cork_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path
  .container
    -flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"

    = yield